### ISSUE TITLE
npm version leads to crash

### ISSUE THREAD

**Issue by maiermic** [Reactive-Extensions/rxjs-jquery#24]
I found two versions on npm: **rx-jquery** and **rxjs-jquery**. Both lead to a crash!
## rx-jquery@1.1.7

```
npm install rx-jquery
```

Call `require('rx-jquery')` results in:

```
.../node_modules/rx-jquery/rx.jquery.js:84
    }  if (!!proto.on) {
                  ^
TypeError: Cannot read property 'on' of undefined
    at .../node_modules/rx-jquery/rx.jquery.js:84:19
    at observable (.../node_modules/rx-jquery/rx.jquery.js:13:26)
    at Object.<anonymous> (.../node_modules/rx-jquery/rx.jquery.js:17:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/rx-jquery/rx.jquery.node.js:2:1)
```
## rxjs-jquery@0.0.3

```
npm install rxjs-jquery
```

Call `require('rxjs-jquery')` results in:

```
.../node_modules/rxjs-jquery/rx.jquery.js:22
        observable = root.Observable,
                         ^
TypeError: Cannot read property 'Observable' of undefined
    at .../node_modules/rxjs-jquery/rx.jquery.js:22:26
    at $ (.../node_modules/rxjs-jquery/rx.jquery.js:13:26)
    at Object.<anonymous> (.../node_modules/rxjs-jquery/rx.jquery.js:17:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../tmp.js:3:11)
```

**Comment by maiermic** [comment]
My fault, I tried to use it in node.js -.-
